#!/usr/bin/expect

set user [lindex $argv 0]
set pass [lindex $argv 1]
set host [lindex $argv 2]
set myip [lindex $argv 3]

spawn ssh -F . -oStrictHostKeyChecking=no $host -l $user
expect -re ".*assword:.*"
send "$pass\n"
expect "\\->"
send_user "\n"
send "nfsUnmount \"/work\"\n"
expect "\\->"
send_user "\n"
send "nfsUnmount \"/opt/fsl_imx6_1_1_6_0_VSB/usr/lib/common\"\n"
expect "\\->"
send_user "\n"
send "hostDelete \"CI\",\"$myip\"\n"
expect "\\->"
send_user "\n"
send "exit\n"

